// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2DKTAeAZaOYfz3OjoqACP60e-jd75GY',
    appId: '1:295999324490:web:1f6ab510aa7e48118e81b3',
    messagingSenderId: '295999324490',
    projectId: 'gameshelf-283dc',
    authDomain: 'gameshelf-283dc.firebaseapp.com',
    storageBucket: 'gameshelf-283dc.firebasestorage.app',
    measurementId: 'G-Q47DKXTYZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe3oYiBHCpRKJd0jLoAhkXKepwfdFa0BU',
    appId: '1:295999324490:android:223231a8b638fa3b8e81b3',
    messagingSenderId: '295999324490',
    projectId: 'gameshelf-283dc',
    storageBucket: 'gameshelf-283dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknhWsRTH2m-lwfJ3wFvkHLWPFikYRe9E',
    appId: '1:295999324490:ios:3d8fa77f031e146d8e81b3',
    messagingSenderId: '295999324490',
    projectId: 'gameshelf-283dc',
    storageBucket: 'gameshelf-283dc.firebasestorage.app',
    androidClientId:
        '295999324490-26508lv18fdgiq23be3q7in07bhu44rv.apps.googleusercontent.com',
    iosClientId:
        '295999324490-s7e31mm8lo7vlsgioafk2fabd1nccdi3.apps.googleusercontent.com',
    iosBundleId: 'com.yujongu.boardGameDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknhWsRTH2m-lwfJ3wFvkHLWPFikYRe9E',
    appId: '1:295999324490:ios:3d8fa77f031e146d8e81b3',
    messagingSenderId: '295999324490',
    projectId: 'gameshelf-283dc',
    storageBucket: 'gameshelf-283dc.firebasestorage.app',
    androidClientId:
        '295999324490-26508lv18fdgiq23be3q7in07bhu44rv.apps.googleusercontent.com',
    iosClientId:
        '295999324490-s7e31mm8lo7vlsgioafk2fabd1nccdi3.apps.googleusercontent.com',
    iosBundleId: 'com.yujongu.boardGameDashboard',
  );
}
